services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: t9pipe
      POSTGRES_USER: jhu
      POSTGRES_PASSWORD: jhu123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: t9pipe
      DB_USER: jhu
      DB_PASSWORD: jhu123
      EIA_API_KEY: ${EIA_API_KEY}
      WEATHER_BASE_URL: ${WEATHER_BASE_URL}
    ports:
      - "8001:8001"

  api_test:
    build: .
    depends_on:
      - app
    environment:
      API_BASE_URL: http://app:8001
    command: [ "python3", "api_smoke_test.py" ]
    profiles:
      - test

volumes:
  postgres_data:
